= bce2(1)
TI\_Eugene (ti.eugene@gmail.com)
v0.0.5
:doctype: manpage
:manmanual: BCE2 Commands Manual
:mansource: BCE2

== Name

bce2 - parse blockchain into text for loading into SQL DB.

== Synopsis

*bce2* [_OPTIONS_]

== Description

Generates text representation of blockchain ready for further loading into SQL database. +
Blockchain can be read as directly from blockchain files (*-d* + *-l* options) as from hex-strings generated by _bitcoin-cli_. +
Intermediate data is storing in key-value files.

== Options

*-h*::
  Help
*-f* _num_::
  Block height to start from (default=0)
*-n* _num_::
  Blocks to process (default=1, all=0)
*-d* _path_::
  blk*.dat folder (conflicts with *-c*)
*-l* _path_::
  Locs-file (conflicts with *-c*)
*-c*::
  Hex input from stdin (conflicts w/ *-d* and *-l*)
*-k* _path_::
  Key-value folder
*-e* _name_::
  Key-value engine (none/kcf/kcm/tkf/tkm, default=none)
*-t* _num_::
  Key-value tuning (depends on engine)
*-o*::
  Generate output (stdout)
*-s* _num_::
  Logging step (default=1)
*-v* _n_::
  Verbosity (0..3, stderr)

== Files

_~/.bce2.cfg_::
  Defaults

== See Also

*btcbklocs*(1), *btclocview*(1), *bce2.cfg*(5)
