= bce2(1)
TI\_Eugene (ti.eugene@gmail.com)
v0.0.5
:doctype: manpage
:manmanual: BCE2 Commands Manual
:mansource: BCE2

== Name

bce2 - parse blockchain into text for loading into SQL DB.

== Synopsis

*bce2* [_OPTIONS_]

== Description

Generates text representation of blockchain ready for further loading into SQL database. +
Blockchain can be read as directly from blockchain files (*-d* + *-l* options) as from hex-strings generated by _bitcoin-cli_ (*-c* option). +
Intermediate data is storing in key-value DB.

== Options

*-h*::
  Help
*-f* _num_::
  Block height to start from (default=0)
*-n* _num_::
  Blocks to process (default=1, all=0)
*-d* _path_::
  blk*.dat folder (conflicts with *-c*)
*-l* _path_::
  Locs-file (conflicts with *-c*)
*-c*::
  Hex input from stdin (conflicts w/ *-d* and *-l*)
*-k* _path_::
  Key-value files base folder
*-e* _name_::
  Key-value engine (none/kcm/kcf/tkm/tkf/bdb, default=none), see below.
*-t* _num_::
  Key-value tuning (depends on engine)
*-o*::
  Generate output (to stdout)
*-s* _num_::
  Logging step, blocks (default=1)
*-v* _n_::
  Verbosity (0..3, default=0, to stderr)
*-m*::
  Multithreading on

=== Key-value engines:

_none_::
  No key-value
_kcm_::
  Kyotocabinet::StashDB - in-memory (depricated)
_kcf_::
  Kyotocabinet::HashDB - on-file (depricated)
_tkm_::
  Tkrzw::SkipDBM - in-memory
_tkf_::
  Tkrzw::HashDBM - on-file
_bdb_::
  BerkeleyDB hash - on-file

== Files

_~/.bce2.cfg_::
  Defaults

== See Also

*btcbklocs*(1), *btclocview*(1), *bce2.cfg*(5)
