.TH btclocview 1 "0.0.5" "TI_Eugene <ti.eugene@gmail.com>" ""
.SH NAME
btclocview \- locsfile viewer
.SH SYNOPSIS
.B btclocbiew
.B <locsfile>
.B <bkno>
.PP
.SH DESCRIPTION
Print location of block according to content of locs\-file \- dat\-file and offset in it..br 
The \fIlocsfile\fR argument is path of locs\-file..br 
The \fIbkno\fR is block height.
.SH AUTHOR
Written by TI_Eugene <ti.eugene@gmail.com>
.SH EXAMPLE
.B$ btclocview bk.locs.650k.bin 10
Bk 10: bk00000.2308.br
(block with height=\fI10\fR is in file \fIbk00000.dat\fR starting from offset \fI2308\fR bytes)
